### PR TITLE
Initial version for tests

### PR DESCRIPTION
**Pull request by fernandohds564**
This PR implements the first version of the code to be tested.

We are still implementing some basic functionalities and the code is still broken, but I think you guys could start contributing by implementing of some parts that we do not have experience here, such as the abstraction layer for `tango`, inside `_control_systems`, or for `pyat`, inside `_simulators`.

Maybe after our meeting on Friday we could also start expanding the definition of other facilities.

### CODE REVIEW

**Comment by swhite2401** [comment]
Hello @fernandohds564 and @murilobalves thanks for the effort!

I started looking at it in more details, in particular the simulator part, there is no problem getting any quantity based on` indices` (or `refpts` in AT) but in AT we are generally calling methods of a `ring` object to access these things which is certainly different than your `facility.accelerator[acc]` object.

To make the link and start building the correct interface my feeling is that `pymodels` is missing here... but maybe I misunderstood how things work, we may discuss this tomorrow.

**Comment by fernandohds564** [comment]
> Hello @fernandohds564 and @murilobalves thanks for the effort!
> 
> I started looking at it in more details, in particular the simulator part, there is no problem getting any quantity based on` indices` (or `refpts` in AT) but in AT we are generally calling methods of a `ring` object to access these things which is certainly different than your `facility.accelerator[acc]` object.
> 
> To make the link and start building the correct interface my feeling is that `pymodels` is missing here... but maybe I misunderstood how things work, we may discuss this tomorrow.

Hi @swhite2401, I'm not sure if I understood correctly, but the object contained in `facility.accelerator[acc]` is not necessarily a `pyaccel` object. It will be a `pyat` model if the simulator of your facility is `pyat`. This model is created by your facility subpackage located inside `_facilities` when the function `set_facility` is called. Every facility can choose the simulator and the control system of interest and also define the mapping from aliases to control system and simulation variables.

Every facility subpackage inside `_facilities` is completely uncoupled from each other, so that they can import any packages needed to define the model and this mapping, without affecting other facilities. In our case, we make use of `pymodels`, but this package will not have any influence when you run the code for your facility.

In practice, you can assume the model returned by `facility.accelerator[acc]` is a `pyat` model for implementing the simulator abstraction layer for `pyat`.

**Comment by swhite2401** [comment]
> > Hello @fernandohds564 and @murilobalves thanks for the effort!
> > I started looking at it in more details, in particular the simulator part, there is no problem getting any quantity based on` indices` (or `refpts` in AT) but in AT we are generally calling methods of a `ring` object to access these things which is certainly different than your `facility.accelerator[acc]` object.
> > To make the link and start building the correct interface my feeling is that `pymodels` is missing here... but maybe I misunderstood how things work, we may discuss this tomorrow.
> 
> Hi @swhite2401, I'm not sure if I understood correctly, but the object contained in `facility.accelerator[acc]` is not necessarily a `pyaccel` object. It will be a `pyat` model if the simulator of your facility is `pyat`. This model is created by your facility subpackage located inside `_facilities` when the function `set_facility` is called. Every facility can choose the simulator and the control system of interest and also define the mapping from aliases to control system and simulation variables.
> 
> Every facility subpackage inside `_facilities` is completely uncoupled from each other, so that they can import any packages needed to define the model and this mapping, without affecting other facilities. In our case, we make use of `pymodels`, but this package will not have any influence when you run the code for your facility.
> 
> In practice, you can assume the model returned by `facility.accelerator[acc]` is a `pyat` model for implementing the simulator abstraction layer for `pyat`.

Ok got it, I though there was some kind of model abstraction defining naming convention for accelerator elements such as DCCT, BPM etc... that we could use for AT as well

**Comment by PierreSchnizer** [comment]
As already in discussion: I second that this is work is merged into main. Simplifies working.

Thanks for the code

**Review by PierreSchnizer — APPROVED** [review]
Thanks for this bunch of code!

**Pull request merged**
